### PR TITLE
Download latest dotnet-install.sh for Linux tests

### LINKED ISSUE #8936: Linux machines failing CI builds due to dotnet-install connection problem
Linux Machines are failing to run Functional Tests when attempting to run dotnet-install.sh.
There appears to be some network configuration or connectivity problem.
`curl: (7) Failed to connect to dotnet.microsoft.com port 443: Connection timed out`

Example failing builds:
https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3298450
https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3298446
https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3298399

As a temporary workaround, I placed the resolved script directly into our build folder: https://github.com/NuGet/Home/issues/8931

[This build](https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_build/results?buildId=3317306) calls  curl -o cli/dotnet-install.sh -L -v https://dot.net/v1/dotnet-install.sh.  curl follows a redirection to https://dotnet.microsoft.com/download/dotnet-core/scripts/v1/dotnet-install.sh but is then unable to reach that URL.

@dtivel  noticed that curl tries using the IPv6 address, so he forced IPv4 in [this build](https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_build/results?buildId=3317526), but the overall failure is still the same.

### PR DESCRIPTION
**Pull request by erdembayar**
## Bug

Fixes: https://github.com/nuget/home/issues/8936

Regression? Last working version: N/A

## Description
Current scripts/funcTests/dotnet-install.sh copy is out of date, we need to download latest copy instead. I removed `-Quality Daily` here since we're passing `Version` parameter. According to [doc](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-install-script#:~:text=%2DVersion%7C%2D%2Dversion%20%3CVERSION%3E) if we pass version then both `channel` and `-Quality Daily` are ignored. Whatever happened with [#971](https://github.com/NuGet/Client.Engineering/issues/971) issue was temporary bug that time for `dotnet-install` script.

## PR Checklist

- [x] PR has a meaningful title
- [x] PR has a linked issue.
- [x] Described changes

- **Tests**
  - [ ] Automated tests added
  - **OR**
  
  - [ ] Test exception
  - **OR**
  - [x] N/A 

- **Documentation**
  
  - [ ] Documentation PR or issue filled
  - **OR**
  - [x] N/A

### CODE REVIEW

File: scripts/funcTests/runFuncTests.sh [hunk 1]
```diff
@@ -81,7 +79,7 @@ do
 
 	echo "Channel is: $Channel"
 	echo "Version is: $Version"
-	scripts/funcTests/dotnet-install.sh -i cli -c $Channel -v $Version -nopath
```
Comment (erdembayar) [inline scripts/funcTests/runFuncTests.sh:84]: I didn't add `-Quality Daily` here since we're passing `Version` parameter. According to [doc](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-install-script#:~:text=%2DVersion%7C%2D%2Dversion%20%3CVERSION%3E) if we pass version then both `channel` and `-Quality Daily` are ignored. Whatever happened with [#971](https://github.com/NuGet/Client.Engineering/issues/971) issue was temporary bug that time. I don't see it happening on my local build today when I removed `-Quality Daily` (I did delete content from NuGet.Client\cli\sdk before this action), that means I can remove `-Quality Daily` below line too, please let me know if it's necessary.
https://github.com/NuGet/NuGet.Client/blob/aa9721f527cb8f25d170d22b8ebaf5e1906cb7fb/build/common.ps1#L258

I can remove `Channel` parameter too here.

Comment (erdembayar) [reply scripts/funcTests/runFuncTests.sh:84]: [14:42:37 +0]   [BEGIN] Installing .NET CLI
[14:42:38 +0]   The version of SDK should be installed is : 5.0.200-servicing.21120.4
[14:42:38 +0]   Probing folder : C:\xxxxxx\NuGet.Client\cli\sdk\5.0.200-servicing.21120.4
[14:42:38 +0]   C:\xxxxxx\NuGet.Client\cli\dotnet-install.ps1 -InstallDir C:\xxxxxx\NuGet.Client\cli -Version 5.0.200-servicing.21120.4 -Architecture x64 -NoPath
dotnet-install: Note that the intended use of this script is for Continuous Integration (CI) scenarios, where:
dotnet-install: - The SDK needs to be installed without user interaction and without admin rights.
dotnet-install: - The SDK installation doesn't need to persist across multiple CI runs.
dotnet-install: To set up a development environment or to run apps, use installers rather than this script. Visit https://dotnet.microsoft.com/download to get the installer.

dotnet-install: Downloading primary link https://dotnetcli.azureedge.net/dotnet/Sdk/5.0.200-servicing.21120.4/dotnet-sdk-5.0.200-servicing.21120.4-win-x64.zip
dotnet-install: Extracting zip from https://dotnetcli.azureedge.net/dotnet/Sdk/5.0.200-servicing.21120.4/dotnet-sdk-5.0.200-servicing.21120.4-win-x64.zip
dotnet-install: Binaries of dotnet can be found in C:\xxxxxx\NuGet.Client\cli\
dotnet-install: Note that the script does not resolve dependencies during installation.
dotnet-install: To check the list of dependencies, go to https://docs.microsoft.com/dotnet/core/install/windows#dependencies
dotnet-install: Installation finished

**Comment by erdembayar** [comment]
Waiting for https://github.com/dotnet/install-scripts/pull/240 get merged.

File: scripts/funcTests/runFuncTests.sh (hunk 1 above)
Comment (erdembayar) [reply scripts/funcTests/runFuncTests.sh:84]: Please check how it looks after removing `-Channel ` and `-Quality Daily` from build/common.ps1

[17:42:18 +1]   Downloading .NET CLI 'release/5.0.2xx:5.0.200-servicing.21120.4'
[17:42:19 +1]   The version of SDK should be installed is : 5.0.200-servicing.21120.4
[17:42:19 +0]   Probing folder : C:xxxxxx\NuGet.Client\cli\sdk\5.0.200-servicing.21120.4
[17:42:19 +0]  ` C:xxxxxx\NuGet.Client\cli\dotnet-install.ps1 -InstallDir C:xxxxxx\NuGet.Client\cli -Version 5.0.200-servicing.21120.4 -Architecture x64 -NoPath`
dotnet-install: Note that the intended use of this script is for Continuous Integration (CI) scenarios, where:
dotnet-install: - The SDK needs to be installed without user interaction and without admin rights.
dotnet-install: - The SDK installation doesn't need to persist across multiple CI runs.
dotnet-install: To set up a development environment or to run apps, use installers rather than this script. Visit https://dotnet.microsoft.com/download to get the installer.

dotnet-install: Downloading primary link https://dotnetcli.azureedge.net/dotnet/Sdk/5.0.200-servicing.21120.4/dotnet-sdk-5.0.200-servicing.21120.4-win-x64.zip
dotnet-install: Extracting zip from https://dotnetcli.azureedge.net/dotnet/Sdk/5.0.200-servicing.21120.4/dotnet-sdk-5.0.200-servicing.21120.4-win-x64.zip
dotnet-install: Binaries of dotnet can be found in C:xxxxxx\NuGet.Client\cli\
dotnet-install: Note that the script does not resolve dependencies during installation.
dotnet-install: To check the list of dependencies, go to https://docs.microsoft.com/dotnet/core/install/windows#dependencies
dotnet-install: Installation finished

File: build/common.ps1 [hunk 2]
```diff
@@ -240,22 +240,8 @@ Function Install-DotnetCLI {
 
         #If "-force" is specified, or folder with specific version doesn't exist, the download command will run"
         if ($Force -or -not (Test-Path $probeDotnetPath)) {
-            $channelMainVersion = ""
```
Comment (nkolev92) [inline build/common.ps1]: Doesn't this logic kill our ability to download the latest version from a channel?

File: scripts/funcTests/runFuncTests.sh (hunk 1 above)
Comment (nkolev92) [reply scripts/funcTests/runFuncTests.sh:84]: We need to be able to download the latest verison from a channel. 

In fact, we usually prefer to do that. 

We tied to the latest version by necessity at some point during the net5 development and never got around to bring it back. @heng-liu is working on the 6.0.

File: build/common.ps1 (hunk 2 above)
Comment (erdembayar) [reply build/common.ps1]: According to [doc](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-install-script#:~:text=%2DVersion%7C%2D%2Dversion%20%3CVERSION%3E) if we pass version then both `channel` and `-Quality Daily` are ignored. So passing `channel` doesn't have any value if we're passing version. Instead we can opt to remove version here, and keep `channel` + `Quality Daily`.

Comment (nkolev92) [reply build/common.ps1]: We want to be testing with channel only. 

Tying the version is something we do, but not something we prefer.

Comment (nkolev92) [reply build/common.ps1]: I see you made a change not using the version right now.

I'm not suggesting we make functional changes, which is what we're doing now. I don't think we should do that. 
We should retain the ability to do both, a version or a channel.

Comment (erdembayar) [reply build/common.ps1]: How we do that? Only 1 is valid at the time. How about read env var to decide?

Comment (heng-liu) [reply build/common.ps1]: Sorry I just noticed this. I also worked on this issue when working on https://github.com/NuGet/Client.Engineering/issues/1271, as the SDK version downloaded from Windows and Linux are different if this issue is not fixed.
Here are the changes might be helpful for reference: ( I tested with both channel or a version, they both work)
[scripts/funcTests/runFuncTests.sh](https://github.com/NuGet/NuGet.Client/compare/dev...dev-hengliu-updateSDKForTestingTo6-useVS2022Pool#diff-290139a5aeb3d6be333f8c728c8b6720cc5802e65eb222a47840eeff298a0fc5)
[build/common.ps1](https://github.com/NuGet/NuGet.Client/compare/dev...dev-hengliu-updateSDKForTestingTo6-useVS2022Pool#diff-75700092c78637e43e3336ed5002de2c6d9b3f5e67f517ccdb4a8aba14cb2b25)
[build/config.props](https://github.com/NuGet/NuGet.Client/compare/dev...dev-hengliu-updateSDKForTestingTo6-useVS2022Pool#diff-bd4ef9ba7459727e37706ab7197bdfaa3868ec01297f168ff0b6e243f087d239)

Comment (heng-liu) [reply build/common.ps1]: BTW, I abandoned lots of logic in build/common.ps1, which is based on the following considerations:
The code is for checking the existing SDK versions in /cli folder before downloading. If the predicted version is already there, it won't download the version again. 
1. The code is not reliable as dotnet installer team might changed the content of URL, or change the URL. We will be in a bad state if there is any change from them.
e.g. the two URLs have different contents, which breaks the script:
https://dotnetcli.blob.core.windows.net/dotnet/Sdk/3.0/latest.version
(two lines, version in the second line)
https://dotnetcli.blob.core.windows.net/dotnet/Sdk/5.0/latest.version)
(only one line, version is the first line)
2. The gain of keeping the code is very small. 
On CI, we will run a clean build every build so the code is useless. 
When we run ./configure.ps1 locally, we usually start with a git clean -xdf command, which makes the code useless, too.
3. The code increases lots of complexity, it doesn't worth doing when the gain is small. (Sorry, but the code is originally added by me. After reconsidering, I think it's good to delete them)

**Review by heng-liu — APPROVED** [review]

File: scripts/funcTests/runFuncTests.sh (hunk 1 above)
Comment (erdembayar) [reply scripts/funcTests/runFuncTests.sh:84]: Considering there's parallel effort going on by Heng, I removed other extra changes, now kept only necessary changes.
Please check now.

**Review by nkolev92 — APPROVED** [review]
