### PR TITLE
Reduce boxing when generating hash code

### LINKED ISSUE #11866: [Bug]: Boxing of structs to compute hashcode is causing excessive allocations
### NuGet Product Used

Other/NA

### Product Version

All

### Worked before?

_No response_

### Impact

Other

### Repro Steps & Context

The HashCodeCombiner takes an object parameter in its AddObject method and when passed a value type such as a struct or enum value, it boxes it to do a null check and then compute the hashcode.  This allocates boxed objects that are short-lived and not necessary.

After the fix for #11669, this becomes one of the top sources of allocation for NuGet restore for some scenarios.

image

image
 

### Verbose Logs

_No response_

### PR DESCRIPTION
**Pull request by wrall**
## Bug

Fixes: https://github.com/NuGet/Home/issues/11866

Regression? Last working version:

## Description
The HashCodeCombiner takes an object parameter in its AddObject method and when passed a value type such as a struct or enum value, it boxes it to do a null check and then compute the hashcode. This allocates boxed objects that are short-lived and not necessary.

After the fix for https://github.com/NuGet/Home/issues/11669, this becomes one of the top sources of allocation for NuGet restore for some scenarios.  See the bug above for "before" picture on allocations.

## PR Checklist

- [x] PR has a meaningful title
- [x] PR has a linked issue.
- [x] Described changes

- **Tests**
  - [ ] Automated tests added
  - **OR**
  - [ ] Test exception
  - **OR**
  - [x] N/A

- **Documentation**
  - [ ] Documentation PR or issue filled
  - **OR**
  - [x] N/A

### CODE REVIEW

**Review by nkolev92 — DISMISSED** [review]

**Review by erdembayar — DISMISSED** [review]
Thank you, great contribution.

**Comment by erdembayar** [comment]
@wrall 
I approved, could you be able to add after improvement memory allocation numbers? It would be great to see what was the delta after this change.

**Comment by nkolev92** [comment]
@erdembayar 

Personally, I'm comfortable merging this as is, regardless of whether the numbers reported large improvements or not. 

Do you care if I merge it?

File: build/Shared/HashCodeCombiner.cs [hunk 1]
```diff
@@ -58,6 +58,15 @@ internal void AddObject<T>(T o)
             }
         }
 
+        // Optimization: for value types, we can avoid boxing "o" by skipping the null check
+        internal void AddStruct<T>(T o)
+            where T : struct
```
Comment (zivkan) [inline build/Shared/HashCodeCombiner.cs:77]: Would adding `where T : class` to `AddObject` prevent people from accidentally trying to use it with a struct?

Comment (erdembayar) [reply build/Shared/HashCodeCombiner.cs:77]: @wrall 
It's your call whether to add it or not.

Comment (wrall) [reply build/Shared/HashCodeCombiner.cs:77]: That's a great idea for enforcement.  I'll make this change.  Note that it will pull in a bunch of other files that weren't showing up in my solution's restore, but could theoretically hit under some scenario.

**Review by nkolev92 — APPROVED** [review]

**Review by zivkan — APPROVED** [review]

**Comment by wrall** [comment]
> @wrall I approved, could you be able to add after improvement memory allocation numbers? It would be great to see what was the delta after this change.

I'm collecting some data now (hopefully sampled will work ok - when I got full allocation details it took over an hour!).  Note that I'm testing performance with this on top of the fix for https://github.com/NuGet/NuGet.Client/pull/4644, even though it looks like this will be merged first.

**Comment by wrall** [comment]
> > @wrall I approved, could you be able to add after improvement memory allocation numbers? It would be great to see what was the delta after this change.
> 
> I'm collecting some data now (hopefully sampled will work ok - when I got full allocation details it took over an hour!). Note that I'm testing performance with this on top of the fix for #4644, even though it looks like this will be merged first.

Unfortunately, sampled mode in dotMemory doesn't seem to count allocations in the way I'm running.  I'll try to get data tonight but would rather not block merging.  I'm fairly sure that those allocations from the bug (~7 GB) will simply disappear.

**Review by erdembayar — APPROVED** [review]

**Comment by wrall** [comment]
@erdembayar - could you please trigger a retry of the failed "Tests on Mac" check?  It looks like it timed out.

**Comment by wrall** [comment]
> It would be great to see what was the delta after this change.

@erdembayar - here are some numbers.

With just https://github.com/NuGet/NuGet.Client/pull/4644 changes:
image
image

With https://github.com/NuGet/NuGet.Client/pull/4666 in addition to https://github.com/NuGet/NuGet.Client/pull/4644 changes:
image
image

|   | Objects (M) | Total Size (GB) | Objects % | Total Size % |
| ------ | ----------- | --------------- | --------- | ------------ |
| Before | 1,235.15    | 68.08           | 100%      | 100%         |
| After  |   997.81    | 61.14           | 80.8%     | 89.8%        |

**Comment by wrall** [comment]
@nkolev92 - let me know if you have any more questions or feedback before merge.  :-)
