### PR TITLE
Linux Machine workaround - include dotnet-install.sh directly in build

### LINKED ISSUE #8931: Temporary Workaround for failing CI due to an issue downloading the dotnet-install script
CI is failing due to an issue downloading the dotnet-install script.
Need a workaround to unblock our builds.

### PR DESCRIPTION
**Pull request by donnie-msft**
## Bug

Fixes: https://github.com/NuGet/Home/issues/8931

## Fix

To unblock our CI, I've uploaded the dotnet-install script to our build folder, and changed the Linux functional tests script to execute that install script directly. This is a workaround for the issue where our Linux machines are having a problem communicating with dotnet endpoint.

### CODE REVIEW

File: scripts/funcTests/runFuncTests.sh [hunk 1]
```diff
@@ -22,13 +22,17 @@ mono --version
...
 # Run install.sh
-chmod +x cli/dotnet-install.sh
+# Issue 8931 chmod +x cli/dotnet-install.sh
+chmod +x scripts/funcTests/dotnet-install.sh
 
 # Get recommended version for bootstrapping testing version
-cli/dotnet-install.sh -i cli -c 2.2
+# Issue 8931 - DISABLED TEMPORARILY cli/dotnet-install.sh -i cli -c 2.2
+scripts/funcTests/dotnet-install.sh -i cli -c 2.2
+echo "pwd=$(pwd)"
```
Comment (dtivel) [inline scripts/funcTests/runFuncTests.sh]: Is this a leftover from your iterating on a solution?

**Review by dtivel — APPROVED** [review]

File: scripts/funcTests/runFuncTests.sh [hunk 2]
```diff
@@ -22,13 +22,15 @@ mono --version
 # Download the CLI install script to cli
 echo "Installing dotnet CLI"
 mkdir -p cli
-curl -o cli/dotnet-install.sh -L https://dot.net/v1/dotnet-install.sh
+# Issue 8931 - DISABLED TEMPORARILY curl -o cli/dotnet-install.sh -L https://dot.net/v1/dotnet-install.sh
```
Comment (nkolev92) [inline scripts/funcTests/runFuncTests.sh]: This should be linking to an issue that tracks the revert of this change :) 
The issue linked will get closed when this PR merges. 

You need 
1. Issue that tracks the adding of the workaround
1. Issue that tracks the removing of the workaround.

Comment (donnie-msft) [reply scripts/funcTests/runFuncTests.sh]: I have both. I just switched the comment to be the thing that undoes the change, not the thing that caused the change.

**Review by nkolev92 — APPROVED** [review]
